version: 2.1

# Define the jobs we want to run for this project
jobs:

  build_and_push:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - checkout
      - run: pwd

      - run: ls -l
      - run: find .
      - run: 
          name: docker build
          command: |
            cd ./10-cicd/circleci/docker
            docker build -t cicd-prueba:latest . 
      - run: 
          name: docker tag
          command: |
            cd ./10-cicd/circleci/docker
            docker tag cicd-prueba:latest videocursoscloud/cicd-prueba:latest 
      - run: 
          name: docker login
          command: |
            cd ./10-cicd/circleci/docker
            docker login --username videocursoscloud --password $DOCKER_PASS              
      - run: 
          name: docker push
          command: |
            cd ./10-cicd/circleci/docker
            docker push videocursoscloud/cicd-prueba:latest                        
workflows:
  build_and_test:
    jobs:
      - build_and_push:
          context: docker-hub-vcc
          